add radio widget
cipchk/nz-schema-form pull request #10
Opened 2018-01-31 08:57 UTC by canaanjin

2018-01-31 09:01 UTC, cipchk requested changes

2018-01-31 09:01 UTC, cipchk commented on lib/src/widgets/radio/radio.widget.ts
> +    <div nz-form-control nz-col [nzSpan]="schema.span_control" [nzOffset]="schema.offset_control">
缺少 `label` 的定义。

2018-01-31 09:01 UTC, cipchk commented on lib/src/widgets/radio/radio.widget.ts
> +    <nz-radio-group [formControl]="control" >
保持一个友好的代码风格，多了一个空格。

2018-01-31 09:01 UTC, cipchk commented on lib/src/widgets/radio/radio.widget.ts
> +            <span [innerText]="option.label"></span>
为什么是 `innerText`?是否 `innerHTML` 会更好一点。

2018-01-31 09:01 UTC, cipchk commented on lib/src/widgets/radio/radio.widget.ts
> +        return this.widgetData['selectList'] || [];
统一使用 `this.widgetData.selectList`

2018-01-31 09:01 UTC, cipchk commented on lib/src/widgets/radio/index.md
> +一般用于是否同意协议。
缺少描述 Schema 部分。

2018-01-31 09:04 UTC, canaanjin commented
感谢 我去完善一下

2018-01-31 09:38 UTC, cipchk commented
建议支持 `nz-radio-button` 及 `nzSize`

2018-01-31 09:40 UTC, cipchk requested changes

2018-01-31 09:40 UTC, cipchk commented on lib/src/widgets/radio/radio.widget.ts
> +                [nzDisabled]="schema.disabled">
每个项都有自己的 `disabled`，而不应该使用 Schema 的 `disabled`。当然也需要处理 Schema 的 `disabled` 表示禁止整个小部件。

2018-02-01 03:18 UTC, cipchk approved these changes

2018-02-01 03:18 UTC, cipchk commented on lib/src/widgets/radio/index.md
>  ## `SelectItem` 属性
建议使用三级目录；因为他是上一级的属性之一。

2018-02-01 03:20 UTC, merged